DROP TABLE IF EXISTS `EXCHANGE`;
CREATE TABLE `EXCHANGE` (
  `EXCHANGE_NAME` varchar(20) NOT NULL,
  PRIMARY KEY  (`EXCHANGE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CURRENCY`;
CREATE TABLE `CURRENCY` (
  `CURRENCY_CODE` varchar(3) NOT NULL,
  PRIMARY KEY  (`CURRENCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ORDER_TYPE`;
CREATE TABLE `ORDER_TYPE` (
  `ORDER_TYPE` varchar(12) NOT NULL,
  PRIMARY KEY  (`ORDER_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `SECURITY_TYPE`;
CREATE TABLE `SECURITY_TYPE` (
  `SECURITY_TYPE` varchar(4) NOT NULL,
  PRIMARY KEY  (`SECURITY_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CONTRACT_BOND`;
CREATE TABLE `CONTRACT_BOND` (
  `CONTRACT_ID` int(11) NOT NULL,
  `CUSIP` varchar(12) NOT NULL,
  `RATINGS` varchar(12) NOT NULL,
  `DESCRIPTION_APPEND` varchar(120) NOT NULL,
  `BOND_TYPE` varchar(12) NOT NULL,
  `COUPON_TYPE` varchar(12) NOT NULL,
  `CALLABLE` tinyint(4) NOT NULL,
  `PUTABLE` tinyint(4) NOT NULL,
  `COUPON` double NOT NULL,
  `CONVERTIBLE` tinyint(4) NOT NULL,
  `MATURITY` varchar(30) NOT NULL,
  `ISSUE_DATE` date NOT NULL,
  `NEXT_OPTION_DATE` date NOT NULL,
  `NEXT_OPTION_TYPE` varchar(30) NOT NULL,
  `NEXT_OPTION_PARTIAL` tinyint(4) NOT NULL,
  `NOTES` varchar(255) default NULL,
  PRIMARY KEY  (`CONTRACT_ID`),
  CONSTRAINT `CB_CON_ID` FOREIGN KEY (`CONTRACT_ID`) REFERENCES `contract` (`CONTRACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONTRACT_EXCHANGE` (
  `CONTRACT_ID` int(11) NOT NULL,
  `EXCHANGE_NAME` varchar(20) NOT NULL,
  PRIMARY KEY  (`CONTRACT_ID`,`EXCHANGE_NAME`),
  KEY `CE_CON_ID` (`CONTRACT_ID`),
  KEY `CE_EXCH` (`EXCHANGE_NAME`),
  CONSTRAINT `CE_CON_ID` FOREIGN KEY (`CONTRACT_ID`) REFERENCES `contract` (`CONTRACT_ID`),
  CONSTRAINT `CE_EXCH` FOREIGN KEY (`EXCHANGE_NAME`) REFERENCES `EXCHANGE` (`EXCHANGE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONTRACT_FUTURE` (
  `CONTRACT_ID` int(11) NOT NULL,
  `EXPIRY` date NOT NULL,
  PRIMARY KEY  (`CONTRACT_ID`),
  CONSTRAINT `CF_CON_ID` FOREIGN KEY (`CONTRACT_ID`) REFERENCES `contract` (`CONTRACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONTRACT_OPTION` (
  `CONTRACT_ID` int(11) NOT NULL,
  `STRIKE` double default NULL,
  `CONTRACT_RIGHT` varchar(3) default NULL,
  PRIMARY KEY  (`CONTRACT_ID`),
  CONSTRAINT `COPT_CON_ID` FOREIGN KEY (`CONTRACT_ID`) REFERENCES `contract` (`CONTRACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CONTRACT_ORDER_TYPE` (
  `CONTRACT_ID` int(11) NOT NULL,
  `ORDER_TYPE` varchar(12) NOT NULL,
  PRIMARY KEY  (`CONTRACT_ID`,`ORDER_TYPE`),
  KEY `CORD_CON_ID` (`CONTRACT_ID`),
  KEY `CORD_ORDER` (`ORDER_TYPE`),
  CONSTRAINT `CORD_CON_ID` FOREIGN KEY (`CONTRACT_ID`) REFERENCES `contract` (`CONTRACT_ID`),
  CONSTRAINT `CORD_ORDER` FOREIGN KEY (`ORDER_TYPE`) REFERENCES `order_type` (`ORDER_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
